# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique_for_date=b'date', verbose_name='Slug')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Publication date')),
                ('short', tinymce.models.HTMLField(blank=True, default=b'', verbose_name='Short description')),
                ('text', tinymce.models.HTMLField(blank=True, default=b'', verbose_name='Full text')),
                ('show', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'ordering': ['-date', 'title'],
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
